[package]
name = "saes-gbot"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15.7"
gcp_auth = "0.12.2"
google-sheets4 = "5.0.5"
reqwest = "0.12.5"
serde = "1.0.204"
serde_json = "1.0.120"
tokio = { version = "1.38.1", features = ["full"] }
