[package]
name = "api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
rocket = { version = "0.5.0", features = ["serde_json"] }
serde = { version = "1.0.198", features = ["derive"] }
sqlx = { version = "0.7.4", features = ["runtime-tokio", "mysql"] }
